#!/bin/sh
# Restore:
# git archive --remote /Pack/git-trautw/trautw.git  master | tar xvfp -
# metastore --apply --empty-dirs --mtime

# set -x

unset SSH_AUTH_SOCK
unset LC_ALL
unset LANG

TMPDIR=/tmp/`basename $0`.$$
mkdir -p $TMPDIR
trap "/bin/rm -rf - $TMPDIR" 0


archive() {
  DIRNAME=$1
  BRANCH="$USER@`hostname``echo $DIRNAME|tr / _`"
  cd $DIRNAME
  echo "Processing `pwd`"
  # Generate a file to check if restores are working
  date +%s > .git_restore_test
  date >> .git_restore_test

  git remote add archive archive:archive.git 2>&1 | grep -v "remote archive already exists."
  git branch $BRANCH 2>&1 | grep -v "fatal: A branch named '$BRANCH' already exists."
  echo '* -text binary' > .gitattributes
  if type metastore >/dev/null 2>&1; then
    metastore -s `find . -maxdepth 1 -name '.git*' -prune -o -name '.metadata' -o -name '.' -o -type l -o -printf "%f "`
  else
    :
    # echo "Warning: metastore not found"
  fi
  git config core.autocrlf false
  git config core.preloadindex true
  git config pack.windowMemory 128m
  # git add --all --force --ignore-errors --verbose
  git add --all --ignore-errors --verbose
  git commit -q -m "`basename $0` `date`" 2>&1 | grep -v 'nothing to commit' | grep -v '# On branch master'
  git -c pack.window=0 -c core.packedGitWindowSize=32m -c core.packedGitLimit=256m -c pack.windowMemory=64m -c pack.packSizeLimit=128m -c gc.auto=0 push archive $BRANCH
  # Now check
  git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --max-count=15
  git archive --format=tar --remote archive:archive.git $BRANCH .git_restore_test | tar xf - -C $TMPDIR
  BACKUPDATE=`cat $TMPDIR/.git_restore_test | head -1`
  NOW=`date +%s`
  AGE=`echo $NOW - $BACKUPDATE | bc`
  if [ "$AGE" -lt 0 -o "$AGE" -gt 7200 ]; then
    echo "ERROR in $0 on `hostname` archiving `pwd`" >&2
    echo "Current:"
    cat .git_restore_test
    echo "Restored:"
    cat $TMPDIR/.git_restore_test
  fi
  /bin/rm $TMPDIR/.git_restore_test
}

for archive in $HOME `test -f $HOME/.paths_to_archive && cat $HOME/.paths_to_archive`; do
  archive $archive
done

# exec rsync -a archive:bin/archive_it $HOME/bin/archive_it
cd $HOME/.gitbackup/gitbackup
git pull -q
